# Generated by Django 5.2.10 on 2026-01-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
